// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "parameters": [
                    {
                        "description": "Expected body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.shortenUrlBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.shortenUrlResponse"
                        }
                    }
                }
            }
        },
        "/:linkId": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id of the link to redirect to",
                        "name": "linkId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirects to the specified link"
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.shortenUrlBody": {
            "type": "object",
            "properties": {
                "fullUrl": {
                    "type": "string"
                }
            }
        },
        "controllers.shortenUrlResponse": {
            "type": "object",
            "properties": {
                "link": {
                    "type": "string"
                },
                "linkId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
